import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


//Components start
import Header from "@/components/Header";
//components end 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "SamDevs",
  description: "Generated by create next app",
};

export default function RootLayout({children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
